M48
; DRILL file {KiCad (6.0.2)} date Sat Mar 19 09:05:25 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-19T09:05:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X66.0Y-56.0
X66.0Y-144.0
X104.0Y-56.0
X104.0Y-144.0
T0
M30
